### Want to generate a table with each region, each subject, number of units recorded and analyzed
- Cleaning up of: /src/wcst_decode/notebooks/20250528_blanche_sam_unit_regions.ipynb
- only include units from sessions actually analyzed
- don't include drifting units

In [24]:
%load_ext autoreload
%autoreload 2

import os
import numpy as np
import pandas as pd
import utils.behavioral_utils as behavioral_utils
import utils.information_utils as information_utils
import utils.visualization_utils as visualization_utils
import utils.pseudo_classifier_utils as pseudo_classifier_utils
import utils.classifier_utils as classifier_utils

import utils.io_utils as io_utils

import utils.glm_utils as glm_utils
from matplotlib import pyplot as plt
import matplotlib
import utils.spike_utils as spike_utils
import utils.subspace_utils as subspace_utils
from trial_splitters.condition_trial_splitter import ConditionTrialSplitter 
from utils.session_data import SessionData
from constants.behavioral_constants import *
from constants.decoding_constants import *
import seaborn as sns
from scripts.pseudo_decoding.belief_partitions.belief_partition_configs import *
import scripts.pseudo_decoding.belief_partitions.belief_partitions_io as belief_partitions_io

import scipy
import argparse
import copy
import plotly.express as px
from scripts.anova_analysis.anova_configs import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

### load units analyzed

In [25]:
def load_units_for_sub(subject, path=UNITS_PATH):
    units = pd.read_pickle(path.format(sub=subject))
    drift_units = pd.read_pickle(DRIFT_PATH.format(sub=subject))
    units = units[~units.PseudoUnitID.isin(drift_units.PseudoUnitID)]
    units = units[~units.structure_level2_cleaned.isin(BAD_REGIONS)]
    feats = pd.read_pickle(FEATS_PATH.format(sub=subject))
    sessions = feats.sessions.explode().unique()
    units = units[units.session.isin(sessions)]
    units = units.rename(columns={'structure_level2': 'Region'})
    units["Region"] = units["Region"].replace({": eexxttrraassttrriiaattee__vviissuuaall__aarreeaass__22--44 ((VV22--VV44))": "extrastriate_visual_areas_2-4 (V2-V4)"})
    units["subject"] = subject
    return units

### load sessions

In [3]:
sa_units = load_units_for_sub("SA")
sa_units_per_region = sa_units.groupby("Region").PseudoUnitID.nunique().reset_index(name="Subject S Units")

In [4]:
bl_units = load_units_for_sub("BL")
bl_units_per_region = bl_units.groupby("Region").PseudoUnitID.nunique().reset_index(name="Subject B Units")

In [16]:
combined = pd.merge(sa_units_per_region, bl_units_per_region, on="Region", how="outer").fillna(0)
combined = pd.merge(sa_units_per_region, bl_units_per_region, on="Region", how="outer").fillna(0)

combined["Subject B Units"] = combined["Subject B Units"].round().astype(int)
combined["Subject S Units"] = combined["Subject S Units"].round().astype(int)
combined["Both Subjects Units"] = combined["Subject B Units"] + combined["Subject S Units"]

totals = pd.DataFrame([{
    "Region": "All", 
    "Subject B Units": combined["Subject B Units"].sum(), 
    "Subject S Units": combined["Subject S Units"].sum(),
    "Both Subjects Units": combined["Both Subjects Units"].sum()
}])
combined = pd.concat((combined, totals))
combined = combined.sort_values(by="Both Subjects Units", ascending=False)

In [17]:
combined

,Region,Subject S Units,Subject B Units,Both Subjects Units
0,All,1089,343,1432
8,lateral_prefrontal_cortex (lat_PFC),239,0,239
6,inferior_temporal_cortex (ITC),185,33,218
9,medial_pallium (MPal),48,129,177
0,amygdala (Amy),73,49,122
2,basal_ganglia (BG),77,38,115
1,anterior_cingulate_gyrus (ACgG),85,7,92
7,lateral_and_ventral_pallium (LVPal),77,6,83
15,superior_parietal_lobule (SPL),61,7,68
11,motor_cortex (motor),63,0,63
13,posterior_medial_cortex (PMC),42,16,58
5,inferior_parietal_lobule (IPL),43,8,51
16,thalamus (Thal),33,12,45
12,orbital_frontal_cortex (OFC),35,0,35
3,extrastriate_visual_areas_2-4 (V2-V4),8,25,33
14,primary_visual_cortex (V1),12,3,15
10,medial_temporal_lobe (MTL),1,9,10
4,floor_of_the_lateral_sulcus (floor_of_ls),7,1,8

In [18]:
combined.to_csv("/data/patrick_res/figures/wcst_paper/units/region_units.csv", index=False)

### Generate a csv of all units and all structure_levels for Mike:

In [19]:
all_units = pd.concat((sa_units, bl_units))

In [20]:
all_units.structure_level2_cleaned.sort_values().unique()

array([':_eexxttrraassttrriiaattee__vviissuuaall__aarreeaass__22--44_VV22--VV44',
       'amygdala_Amy', 'anterior_cingulate_gyrus_ACgG',
       'basal_ganglia_BG', 'extrastriate_visual_areas_2-4_V2-V4',
       'floor_of_the_lateral_sulcus_floor_of_ls',
       'inferior_parietal_lobule_IPL', 'inferior_temporal_cortex_ITC',
       'lateral_and_ventral_pallium_LVPal',
       'lateral_prefrontal_cortex_lat_PFC', 'medial_pallium_MPal',
       'medial_temporal_lobe_MTL', 'motor_cortex_motor',
       'orbital_frontal_cortex_OFC', 'posterior_medial_cortex_PMC',
       'primary_visual_cortex_V1', 'superior_parietal_lobule_SPL',
       'thalamus_Thal'], dtype=object)

In [21]:
all_units.to_csv("/data/patrick_res/figures/wcst_paper/units/all_units.csv", index=False)

In [22]:
all_units.columns

Index(['Channel', 'Unit', 'SpikeTimesFile', 'UnitID', 'electrode_id', 'x', 'y',
       'z', 'distance', 'in_brain', 'tissue', 'structure_level1', 'Region',
       'structure_level3', 'structure_level4', 'structure_level5',
       'structure_level6', 'structure_potential', 'session', 'PseudoUnitID',
       'structure_level2_cleaned', 'manual_structure',
       'manual_structure_cleaned', 'drive', 'subject'],
      dtype='object')

### Generate a table including BL corrected regions

In [26]:
BL_CORRECTED_PATH = "/data/patrick_res/firing_rates/{sub}/all_units_corrected.pickle"

sa_units = load_units_for_sub("SA")
sa_units_per_region = sa_units.groupby("Region").PseudoUnitID.nunique().reset_index(name="Subject S Units")

bl_original_units = load_units_for_sub("BL")
bl_original_units_per_region = bl_original_units.groupby("Region").PseudoUnitID.nunique().reset_index(name="Subject B Units Original")

bl_correct_units = load_units_for_sub("BL", path=BL_CORRECTED_PATH)
bl_correct_units_per_region = bl_correct_units.groupby("Region").PseudoUnitID.nunique().reset_index(name="Subject B Units Corrected")

In [27]:
combined = pd.merge(sa_units_per_region, bl_original_units_per_region, on="Region", how="outer").fillna(0)
combined = pd.merge(combined, bl_correct_units_per_region, on="Region", how="outer").fillna(0)

combined["Subject B Units Original"] = combined["Subject B Units Original"].round().astype(int)
combined["Subject B Units Corrected"] = combined["Subject B Units Corrected"].round().astype(int)
combined["Subject B Diff"] = combined["Subject B Units Corrected"] - combined["Subject B Units Original"]

combined["Subject S Units"] = combined["Subject S Units"].round().astype(int)
combined["Both Subjects Units Corrected"] = combined["Subject B Units Corrected"] + combined["Subject S Units"]

totals = pd.DataFrame([{
    "Region": "All", 
    "Subject B Units Original": combined["Subject B Units Original"].sum(), 
    "Subject B Units Corrected": combined["Subject B Units Corrected"].sum(), 
    "Subject B Diff": combined["Subject B Diff"].sum(), 
    "Subject S Units": combined["Subject S Units"].sum(),
    "Both Subjects Units Corrected": combined["Both Subjects Units Corrected"].sum()
}])
combined = pd.concat((combined, totals))
combined = combined.sort_values(by="Both Subjects Units Corrected", ascending=False)

In [28]:
combined.to_csv("/data/patrick_res/figures/wcst_paper/units/region_units_bl_corrected.csv", index=False)

In [29]:
all_units_correct = pd.concat((sa_units, bl_correct_units))
all_units_correct.to_csv("/data/patrick_res/figures/wcst_paper/units/all_units_correct.csv", index=False)

In [30]:
combined.sort_values

,Region,Subject S Units,Subject B Units Original,Subject B Units Corrected,Subject B Diff,Both Subjects Units Corrected
0,All,1089,343,333,-10,1422
6,inferior_temporal_cortex (ITC),185,33,56,23,241
8,lateral_prefrontal_cortex (lat_PFC),239,0,0,0,239
9,medial_pallium (MPal),48,129,83,-46,131
2,basal_ganglia (BG),77,38,34,-4,111
0,amygdala (Amy),73,49,24,-25,97
1,anterior_cingulate_gyrus (ACgG),85,7,0,-7,85
7,lateral_and_ventral_pallium (LVPal),77,6,7,1,84
15,superior_parietal_lobule (SPL),61,7,16,9,77
11,motor_cortex (motor),63,0,0,0,63
13,posterior_medial_cortex (PMC),42,16,15,-1,57
5,inferior_parietal_lobule (IPL),43,8,11,3,54
16,thalamus (Thal),33,12,16,4,49
12,orbital_frontal_cortex (OFC),35,0,0,0,35
3,extrastriate_visual_areas_2-4 (V2-V4),8,25,25,0,33
14,primary_visual_cortex (V1),12,3,16,13,28
10,medial_temporal_lobe (MTL),1,9,23,14,24
4,floor_of_the_lateral_sulcus (floor_of_ls),7,1,7,6,14